<?php

require_once dirname(__FILE__) . '/../../../../php/utils/formElementUtils.php';

/**
 * Test class for formElementUtils.
 * Generated by PHPUnit on 2012-08-19 at 15:09:31.
 */
class formElementUtilsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var formElementUtils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new formElementUtils;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers formElementUtils::getTextFieldSection
     * @todo Implement testGetTextFieldSection().
     */
    public function testGetTextFieldSection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers formElementUtils::getTextField
     * @todo Implement testGetTextField().
     */
    public function testGetTextField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers formElementUtils::getTextAreaSection
     * @todo Implement testGetTextAreaSection().
     */
    public function testGetTextAreaSection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers formElementUtils::getHiddenField
     * @todo Implement testGetHiddenField().
     */
    public function testGetHiddenField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers formElementUtils::getLabel
     * @todo Implement testGetLabel().
     */
    public function testGetLabel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
