<?php

require_once dirname(__FILE__) . '/../../../../php/utils/HTTPDigest.php';

/**
 * Test class for HTTPDigest.
 * Generated by PHPUnit on 2012-08-19 at 15:09:31.
 */
class HTTPDigestTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HTTPDigest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HTTPDigest;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers HTTPDigest::send
     * @todo Implement testSend().
     */
    public function testSend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTTPDigest::getAuthHeader
     * @todo Implement testGetAuthHeader().
     */
    public function testGetAuthHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTTPDigest::authenticate
     * @todo Implement testAuthenticate().
     */
    public function testAuthenticate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTTPDigest::getNonce
     * @todo Implement testGetNonce().
     */
    public function testGetNonce() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTTPDigest::getOpaque
     * @todo Implement testGetOpaque().
     */
    public function testGetOpaque() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HTTPDigest::getRealm
     * @todo Implement testGetRealm().
     */
    public function testGetRealm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
