<?php

require_once dirname(__FILE__) . '/../../../../php/utils/stringUtils.php';

/**
 * Test class for stringUtils.
 * Generated by PHPUnit on 2012-08-19 at 15:09:31.
 */
class stringUtilsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var stringUtils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new stringUtils;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers stringUtils::htmlToText
     * @todo Implement testHtmlToText().
     */
    public function testHtmlToText() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers stringUtils::textToHtml
     * @todo Implement testTextToHtml().
     */
    public function testTextToHtml() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
