<?php

require_once dirname(__FILE__) . '/../../../../php/model/conferenceDay.php';

/**
 * Test class for conferenceDay.
 * Generated by PHPUnit on 2012-08-19 at 15:09:33.
 */
class conferenceDayTest extends PHPUnit_Framework_TestCase {

    /**
     * @var conferenceDay
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new conferenceDay;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers conferenceDay::set_day
     * @todo Implement testSet_day().
     */
    public function testSet_day() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers conferenceDay::get_day
     * @todo Implement testGet_day().
     */
    public function testGet_day() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers conferenceDay::add_session
     * @todo Implement testAdd_session().
     */
    public function testAdd_session() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers conferenceDay::get_sessions
     * @todo Implement testGet_sessions().
     */
    public function testGet_sessions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers conferenceDay::get_sessionAt
     * @todo Implement testGet_sessionAt().
     */
    public function testGet_sessionAt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
