<?php

require_once dirname(__FILE__) . '/../../../../php/model/conference.php';

/**
 * Test class for conference.
 * Generated by PHPUnit on 2012-08-19 at 15:09:34.
 */
class conferenceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var conference
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new conference;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers conference::add_conferenceDay
     * @todo Implement testAdd_conferenceDay().
     */
    public function testAdd_conferenceDay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers conference::get_conferenceDays
     * @todo Implement testGet_conferenceDays().
     */
    public function testGet_conferenceDays() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers conference::get_conferenceDayAt
     * @todo Implement testGet_conferenceDayAt().
     */
    public function testGet_conferenceDayAt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
