<?php

require_once dirname(__FILE__) . '/../../../../php/model/hotel.php';

/**
 * Test class for hotel.
 * Generated by PHPUnit on 2012-08-19 at 15:09:34.
 */
class hotelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var hotel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new hotel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers hotel::set_id
     * @todo Implement testSet_id().
     */
    public function testSet_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hotel::get_id
     * @todo Implement testGet_id().
     */
    public function testGet_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hotel::set_header
     * @todo Implement testSet_header().
     */
    public function testSet_header() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hotel::get_header
     * @todo Implement testGet_header().
     */
    public function testGet_header() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hotel::set_ingress
     * @todo Implement testSet_ingress().
     */
    public function testSet_ingress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hotel::get_ingress
     * @todo Implement testGet_ingress().
     */
    public function testGet_ingress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hotel::set_content
     * @todo Implement testSet_content().
     */
    public function testSet_content() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hotel::get_content
     * @todo Implement testGet_content().
     */
    public function testGet_content() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hotel::set_footer
     * @todo Implement testSet_footer().
     */
    public function testSet_footer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers hotel::get_footer
     * @todo Implement testGet_footer().
     */
    public function testGet_footer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
