<?php

require_once dirname(__FILE__) . '/../../../../php/model/info.php';

/**
 * Test class for info.
 * Generated by PHPUnit on 2012-08-19 at 15:09:33.
 */
class infoTest extends PHPUnit_Framework_TestCase {

    /**
     * @var info
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new info;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers info::set_id
     * @todo Implement testSet_id().
     */
    public function testSet_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers info::get_id
     * @todo Implement testGet_id().
     */
    public function testGet_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers info::set_header
     * @todo Implement testSet_header().
     */
    public function testSet_header() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers info::get_header
     * @todo Implement testGet_header().
     */
    public function testGet_header() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers info::set_ingress
     * @todo Implement testSet_ingress().
     */
    public function testSet_ingress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers info::get_ingress
     * @todo Implement testGet_ingress().
     */
    public function testGet_ingress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers info::set_content1
     * @todo Implement testSet_content1().
     */
    public function testSet_content1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers info::get_content1
     * @todo Implement testGet_content1().
     */
    public function testGet_content1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers info::set_content2
     * @todo Implement testSet_content2().
     */
    public function testSet_content2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers info::get_content2
     * @todo Implement testGet_content2().
     */
    public function testGet_content2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers info::set_mapHeader
     * @todo Implement testSet_mapHeader().
     */
    public function testSet_mapHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers info::get_mapHeader
     * @todo Implement testGet_mapHeader().
     */
    public function testGet_mapHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers info::set_map
     * @todo Implement testSet_map().
     */
    public function testSet_map() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers info::get_map
     * @todo Implement testGet_map().
     */
    public function testGet_map() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers info::set_footer
     * @todo Implement testSet_footer().
     */
    public function testSet_footer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
