<?php

require_once dirname(__FILE__) . '/../../../../php/model/session.php';

/**
 * Test class for session.
 * Generated by PHPUnit on 2012-08-19 at 15:09:33.
 */
class sessionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var session
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new session;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers session::set_id
     * @todo Implement testSet_id().
     */
    public function testSet_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::get_id
     * @todo Implement testGet_id().
     */
    public function testGet_id() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::set_start
     * @todo Implement testSet_start().
     */
    public function testSet_start() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::get_start
     * @todo Implement testGet_start().
     */
    public function testGet_start() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::set_startTime
     * @todo Implement testSet_startTime().
     */
    public function testSet_startTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::get_startTime
     * @todo Implement testGet_startTime().
     */
    public function testGet_startTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::set_endTime
     * @todo Implement testSet_endTime().
     */
    public function testSet_endTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::get_endTime
     * @todo Implement testGet_endTime().
     */
    public function testGet_endTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::set_name
     * @todo Implement testSet_name().
     */
    public function testSet_name() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::get_name
     * @todo Implement testGet_name().
     */
    public function testGet_name() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::set_speaker
     * @todo Implement testSet_speaker().
     */
    public function testSet_speaker() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::get_speaker
     * @todo Implement testGet_speaker().
     */
    public function testGet_speaker() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::set_timestamp
     * @todo Implement testSet_timestamp().
     */
    public function testSet_timestamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::get_timestamp
     * @todo Implement testGet_timestamp().
     */
    public function testGet_timestamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::set_ingress
     * @todo Implement testSet_ingress().
     */
    public function testSet_ingress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::get_ingress
     * @todo Implement testGet_ingress().
     */
    public function testGet_ingress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::set_description
     * @todo Implement testSet_description().
     */
    public function testSet_description() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::get_description
     * @todo Implement testGet_description().
     */
    public function testGet_description() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::set_place
     * @todo Implement testSet_place().
     */
    public function testSet_place() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::get_place
     * @todo Implement testGet_place().
     */
    public function testGet_place() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::set_dateCreated
     * @todo Implement testSet_dateCreated().
     */
    public function testSet_dateCreated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers session::get_dateCreated
     * @todo Implement testGet_dateCreated().
     */
    public function testGet_dateCreated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
