<?php

require_once dirname(__FILE__) . '/../../../../php/persistence/storage.php';
require_once dirname(__FILE__) . '/../../../../php/config/config.php';

/**
 * Test class for storage.
 * Generated by PHPUnit on 2012-08-19 at 15:09:32.
 */
class storageTest extends PHPUnit_Framework_TestCase {

    /**
     * @var storage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new storage;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers storage::getContent
     * @todo Implement testGetContent().
     */    
    public function testGetContent() {
        $this->assertNotNull($this->object->getContent(config::RESOURCE_PATH."hotel.json"));
        $this->assertNotNull($this->object->getContent(config::RESOURCE_PATH."info.json"));
        $this->assertNotNull($this->object->getContent(config::RESOURCE_PATH."agenda.json"));
        $this->assertEquals($this->object->getContent(config::RESOURCE_PATH."nonexisting.json"), false);
    }

    /**
     * @covers storage::saveContent
     * @todo Implement testSaveContent().
     */
    public function testSaveContent() {
    }

}

?>
